export const Cities = [
  { id: 1, value: "Ariana" },
  { id: 2, value: "Ben Arous" },
  { id: 3, value: "Tunis" },
  { id: 4, value: "Manouba" },
  { id: 5, value: "Sfax" },
  { id: 6, value: "Béja" },
  { id: 7, value: "Bizerte" },
  { id: 8, value: "Gabes" },
  { id: 9, value: "Gafsa" },
  { id: 10, value: "Jendouba" },
  { id: 11, value: "Kairaouan" },
  { id: 12, value: "Kasserine" },
  { id: 13, value: "Kébili" },
  { id: 14, value: "Le Kef" },
  { id: 15, value: "Mahdia" },
  { id: 16, value: "Médenine" },
  { id: 17, value: "Monastir" },
  { id: 18, value: "Nabeul" },
  { id: 19, value: "Sidi Bouzid" },
  { id: 20, value: "Siliana" },
  { id: 21, value: "Sousse" },
  { id: 22, value: "Tataouine" },
  { id: 23, value: "Tozeur" },
  { id: 24, value: "Zaghouan" },
];
