export const Cities = [
  { value: "Ariana" },
  { value: "Ben Arous" },
  { value: "Tunis" },
  { value: "Manouba" },
  { value: "Sfax" },
  { value: "Béja" },
  { value: "Bizerte" },
  { value: "Gabes" },
  { value: "Gafsa" },
  { value: "Jendouba" },
  { value: "Kairaouan" },
  { value: "Kasserine" },
  { value: "Kébili" },
  { value: "Le Kef" },
  { value: "Mahdia" },
  { value: "Médenine" },
  { value: "Monastir" },
  { value: "Nabeul" },
  { value: "Sidi Bouzid" },
  { value: "Siliana" },
  { value: "Sousse" },
  { value: "Tataouine" },
  { value: "Tozeur" },
  { value: "Zaghouan" },
];
